# Generated by Django 2.2.7 on 2020-01-05 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('para_main', models.TextField(max_length=200)),
                ('para_1', models.TextField(blank=True, max_length=200)),
                ('para_2', models.TextField(blank=True, max_length=200)),
                ('para_3', models.TextField(blank=True, max_length=200)),
                ('para_4', models.TextField(blank=True, max_length=200)),
                ('para_5', models.TextField(blank=True, max_length=200)),
                ('para_6', models.TextField(blank=True, max_length=200)),
                ('para_7', models.TextField(blank=True, max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/claims/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
