# Generated by Django 2.2.7 on 2019-12-02 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('point_main', models.CharField(max_length=200)),
                ('point_1', models.CharField(blank=True, max_length=200)),
                ('point_2', models.CharField(blank=True, max_length=200)),
                ('point_3', models.CharField(blank=True, max_length=200)),
                ('point_4', models.CharField(blank=True, max_length=200)),
                ('point_5', models.CharField(blank=True, max_length=200)),
                ('point_6', models.CharField(blank=True, max_length=200)),
                ('point_7', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/claims/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
