# Generated by Django 2.2.7 on 2020-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='para_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para_main',
            field=models.TextField(),
        ),
    ]
