# Generated by Django 2.2.7 on 2019-12-02 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_header', models.CharField(max_length=150)),
                ('home_content', models.TextField()),
                ('consulting_content', models.TextField()),
                ('assistance_content', models.TextField()),
                ('queries_content', models.TextField()),
                ('about_heading', models.CharField(max_length=150)),
                ('about_content_1', models.TextField()),
                ('about_photo', models.ImageField(upload_to='photos/pages/%Y/%m/%d/')),
                ('about_content_2', models.TextField()),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
